/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-05-09 18:05:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/top-navbar.html", Long.valueOf(1746805546889L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1746792076384L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("    <title>e_Hotel Luxury Stay</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" />\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- Top Navigation -->\n");
      out.write("<!-- top-navbar.html -->\n");
      out.write("<nav class=\"top-nav\">\n");
      out.write("    <a href=\"#welcome-section\" class=\"logo nav-link\">VELVET NIGHTS</a>\n");
      out.write("    <ul>\n");
      out.write("       <!-- <li><a href=\"#welcome-section\">Home</a></li> -->\n");
      out.write("        <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("        <li><a href=\"rooms.jsp\">Rooms</a></li>\n");
      out.write("        <li><a href=\"contact.jsp\">Contact</a></li>\n");
      out.write("        <li><a href=\"login.jsp\">Login</a></li>\n");
      out.write("    </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Hero Video Section -->\n");
      out.write("<section class=\"video-section\">\n");
      out.write("    <video autoplay muted loop id=\"background-video\" poster=\"media/poster.jpg\">\n");
      out.write("        <source src=\"media/background.mp4\" type=\"video/mp4\" />\n");
      out.write("        Your browser does not support the video tag.\n");
      out.write("    </video>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- Additional Scrollable Content -->\n");
      out.write("<section id=\"welcome-section\" class=\"welcome-section\">\n");
      out.write("    <h2>VELVET NIGHTS</h2>\n");
      out.write("    <br><br>\n");
      out.write("    <p class=\"description\">\n");
      out.write("        Step into a world where sophistication, comfort, and timeless elegance blend seamlessly.\n");
      out.write("        At <b>Velvet Nights</b>, we believe your stay should be more than just accommodation.\n");
      out.write("        It should be an experience. From lavish interiors and curated details to warm service and serene ambiance,\n");
      out.write("        every element is designed to immerse you in luxury.\n");
      out.write("        Whether you are here for a weekend escape, a romantic getaway, or a business retreat,\n");
      out.write("        let us redefine what it means to feel at home, wrapped in velvet and surrounded by beauty.\n");
      out.write("    </p>\n");
      out.write("    <button class=\"info-btn\" onclick=\"location.href='rooms.jsp'\">BOOK A ROOM</button>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section class=\"highlight-section\">\n");
      out.write("    <div class=\"highlight-container\">\n");
      out.write("        <div class=\"highlight-image\">\n");
      out.write("            <img src=\"media/hotel-building.png\" alt=\"Velvet Nights Hotel in Ottawa\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"highlight-text\">\n");
      out.write("            <h3>ELEGANCE MEETS NATURE IN THE HEART OF OTTAWA</h3>\n");
      out.write("            <p>\n");
      out.write("                At Velvet Nights, every stay is a statement of comfort and consciousness. Our upcoming location\n");
      out.write("                blends timeless luxury with natural serenity, nestled near Ottawaâs historic waterways and vibrant city life.\n");
      out.write("            </p>\n");
      out.write("            <p>\n");
      out.write("                From curated interiors to sustainable design choices, we invite you to discover a hotel experience\n");
      out.write("                that embraces sophistication and soul.\n");
      out.write("            </p>\n");
      out.write("            <p>- Velvet Nights Editorial</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section class=\"highlight-section\">\n");
      out.write("    <div class=\"highlight-container\">\n");
      out.write("        <div class=\"highlight-image\">\n");
      out.write("            <img src=\"media/dining.png\" alt=\"Velvet Nights Gourmet Dining\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"highlight-text\">\n");
      out.write("            <h3>CULINARY DELIGHTS THAT TELL A STORY</h3>\n");
      out.write("            <p>\n");
      out.write("                At Velvet Nights, dining is more than a meal â itâs an experience. From locally inspired dishes to international favorites, every plate is crafted to awaken your senses. Whether itâs breakfast in bed or dinner under the stars, your taste journey begins here.\n");
      out.write("            </p>\n");
      out.write("            <p>- Velvet Nights Culinary Team</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section class=\"highlight-section\">\n");
      out.write("    <div class=\"highlight-container\">\n");
      out.write("        <div class=\"highlight-image\">\n");
      out.write("            <img src=\"media/spaRoom.png\" alt=\"Velvet Nights Gourmet Dining\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"highlight-text\">\n");
      out.write("            <h3>YOUR PEACEFUL HAVEN IN THE CITY</h3>\n");
      out.write("            <p>\n");
      out.write("                Step away from the noise and into serenity. Our wellness offerings include in-room spa treatments,\n");
      out.write("                guided meditation sessions, and access to nearby nature walks. Velvet Nights is where body, mind,\n");
      out.write("                and soul find balance.\n");
      out.write("            </p>\n");
      out.write("            <p>- Velvet Nights Wellness Team</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section class=\"highlight-section\">\n");
      out.write("    <div class=\"highlight-container\">\n");
      out.write("        <div class=\"highlight-image\">\n");
      out.write("            <img src=\"media/img.png\" alt=\"Velvet Nights Gourmet Dining\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"highlight-text\">\n");
      out.write("            <h3>CELEBRATING MOMENTS THAT MATTER</h3>\n");
      out.write("            <p>\n");
      out.write("                From bridal mornings and best-friend getaways to spontaneous escapes, Velvet Nights is where\n");
      out.write("                unforgettable memories begin.\n");
      out.write("            </p>\n");
      out.write("            <p>Laughter, comfort, and a touch of luxury â all wrapped in moments that feel like magic. </p>\n");
      out.write("            <p>Every smile here tells a story, and yours is just getting started.</p>\n");
      out.write("            <p>- Velvet Nights Wellness Team</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"js/script.js\"></script>\n");
      out.write("<!-- Footer -->\n");
      out.write("<footer style=\"text-align:center; padding: 30px 0; background-color: white; color: #111; font-size: 14px;\">\n");
      out.write("    &copy; 2025 Kairly Tawk. All rights reserved.\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
