/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-05-09 18:08:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class manageHotels_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin-navbar.html", Long.valueOf(1746813715680L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Manage Hotels</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; padding: 20px; background: #f9f9f9; }\n");
      out.write("        h2 { color: #333; }\n");
      out.write("        .nav { background: #eaf7ea; padding: 10px; margin-bottom: 20px; border-radius: 5px; }\n");
      out.write("        .nav a { margin-right: 15px; color: #0a0a0a; font-weight: bold; text-decoration: none; }\n");
      out.write("        .card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 30px; }\n");
      out.write("        label { display: inline-block; width: 120px; margin-bottom: 10px; }\n");
      out.write("        input[type=\"text\"] { width: 250px; padding: 6px; border: 1px solid #ccc; border-radius: 4px; margin-bottom: 10px; }\n");
      out.write("        input[type=\"submit\"], button { background: #0a0a0a; color: white; border: none; padding: 8px 12px; border-radius: 4px; cursor: pointer; }\n");
      out.write("        input[type=\"submit\"]:hover, button:hover { background: #0a0a0a; }\n");
      out.write("        table { width: 100%; border-collapse: collapse; background: white; border-radius: 5px; overflow: hidden; }\n");
      out.write("        th, td { padding: 10px; border-bottom: 1px solid #ddd; text-align: left; }\n");
      out.write("        th { background-color: #f2f2f2; }\n");
      out.write("        tr:hover { background-color: #f1f1f1; }\n");
      out.write("        .modal { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); justify-content: center; align-items: center; }\n");
      out.write("        .modal-content { background: white; padding: 20px; border-radius: 5px; width: 400px; }\n");
      out.write("        .close { float: right; cursor: pointer; color: red; font-weight: bold; }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        function openEditModal(id, name, chain, address, stars, area, category, manager) {\n");
      out.write("            document.getElementById(\"editId\").value = id;\n");
      out.write("            document.getElementById(\"editName\").value = name;\n");
      out.write("            document.getElementById(\"editChain\").value = chain;\n");
      out.write("            document.getElementById(\"editAddress\").value = address;\n");
      out.write("            document.getElementById(\"editStars\").value = stars;\n");
      out.write("            document.getElementById(\"editArea\").value = area;\n");
      out.write("            document.getElementById(\"editCategory\").value = category;\n");
      out.write("            document.getElementById(\"editManager\").value = manager;\n");
      out.write("            document.getElementById(\"editModal\").style.display = \"flex\";\n");
      out.write("        }\n");
      out.write("        function closeModal() {\n");
      out.write("            document.getElementById(\"editModal\").style.display = \"none\";\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Navbar</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            font-family: 'Helvetica Neue', sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .navbar {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            background-color: #222;\n");
      out.write("            padding: 1rem 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .navbar .logo {\n");
      out.write("            color: #fff;\n");
      out.write("            font-size: 20px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .navbar ul {\n");
      out.write("            list-style: none;\n");
      out.write("            display: flex;\n");
      out.write("            gap: 1.5rem;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .navbar ul li a {\n");
      out.write("            color: #fff;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: color 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .navbar ul li a:hover {\n");
      out.write("            color: #f0a500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .navbar .logo a {\n");
      out.write("            color: #fff;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .navbar .logo a:hover {\n");
      out.write("            color: #f0a500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("    <div class=\"logo\">\n");
      out.write("        <a href=\"index.jsp\">VELVET NIGHTS</a>\n");
      out.write("    </div>\n");
      out.write("    <ul>\n");
      out.write("        <li><a href=\"manageCustomers.jsp\">Manage Customers</a></li>\n");
      out.write("        <li><a href=\"manageEmployees.jsp\">Manage Employees</a></li>\n");
      out.write("        <li><a href=\"manageHotels.jsp\">Manage Hotels</a></li>\n");
      out.write("        <li><a href=\"manageRooms.jsp\">Manage Rooms</a></li>\n");
      out.write("    </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<h2>Manage Hotels</h2>\n");
      out.write("\n");
      out.write("<!-- INSERT HOTEL -->\n");
      out.write("<div class=\"card\">\n");
      out.write("    <h3>Insert Hotel</h3>\n");
      out.write("    <form method=\"post\">\n");
      out.write("        <label>Hotel Name:</label><input type=\"text\" name=\"insert_name\" required><br>\n");
      out.write("        <label>Chain Name:</label><input type=\"text\" name=\"insert_chain\" required><br>\n");
      out.write("        <label>Address:</label><input type=\"text\" name=\"insert_address\" required><br>\n");
      out.write("        <label>Stars:</label><input type=\"text\" name=\"insert_stars\"><br>\n");
      out.write("        <label>Area:</label><input type=\"text\" name=\"insert_area\" required><br>\n");
      out.write("        <label>Category:</label><input type=\"text\" name=\"insert_category\"><br>\n");
      out.write("        <label>Manager SIN:</label><input type=\"text\" name=\"insert_manager\"><br>\n");
      out.write("        <input type=\"submit\" name=\"action\" value=\"Insert\">\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Display All Hotels -->\n");
      out.write("<table>\n");
      out.write("    <tr>\n");
      out.write("        <th>ID</th><th>Name</th><th>Chain</th><th>Address</th><th>Stars</th><th>Area</th><th>Category</th><th>Manager</th><th>Actions</th>\n");
      out.write("    </tr>\n");
      out.write("    ");

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/e_hotel_system", "postgres", "password");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM hotels");
            while (rs.next()) {
                String id = rs.getString("hotel_id");
                String name = rs.getString("hotel_name");
                String chain = rs.getString("chain_name");
                String address = rs.getString("hotel_address");
                String stars = rs.getString("stars");
                String area = rs.getString("area");
                String category = rs.getString("category");
                String manager = rs.getString("manager_sin");
    
      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td>");
      out.print( id );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( name );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( chain );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( address );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( stars );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( area );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( category );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( manager );
      out.write("</td>\n");
      out.write("        <td>\n");
      out.write("            <button type=\"button\" onclick=\"openEditModal('");
      out.print( id );
      out.write("', '");
      out.print( name );
      out.write("', '");
      out.print( chain );
      out.write("', '");
      out.print( address );
      out.write("', '");
      out.print( stars );
      out.write("', '");
      out.print( area );
      out.write("', '");
      out.print( category );
      out.write("', '");
      out.print( manager );
      out.write("')\">Edit</button>\n");
      out.write("            <form method=\"post\" style=\"display:inline;\"\n");
      out.write("                  onsubmit='return confirm(\"Are you sure you want to delete hotel ");
      out.print( name );
      out.write(" (ID: ");
      out.print( id );
      out.write(")?\");'>\n");
      out.write("                <input type=\"hidden\" name=\"delete_id\" value=\"");
      out.print( id );
      out.write("\"/>\n");
      out.write("                <input type=\"submit\" name=\"action\" value=\"Delete\">\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("    ");

            }
        } catch (Exception e) {
            out.println("<tr><td colspan='9'>Error loading hotels: " + e.getMessage() + "</td></tr>");
        } finally {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (conn != null) conn.close();
        }
    
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<!-- Edit Modal -->\n");
      out.write("<div id=\"editModal\" class=\"modal\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\n");
      out.write("        <h3>Edit Hotel</h3>\n");
      out.write("        <form method=\"post\">\n");
      out.write("            <input type=\"hidden\" id=\"editId\" name=\"update_id\">\n");
      out.write("            <label>Name:</label><input type=\"text\" id=\"editName\" name=\"update_name\"><br>\n");
      out.write("            <label>Chain:</label><input type=\"text\" id=\"editChain\" name=\"update_chain\"><br>\n");
      out.write("            <label>Address:</label><input type=\"text\" id=\"editAddress\" name=\"update_address\"><br>\n");
      out.write("            <label>Stars:</label><input type=\"text\" id=\"editStars\" name=\"update_stars\"><br>\n");
      out.write("            <label>Area:</label><input type=\"text\" id=\"editArea\" name=\"update_area\"><br>\n");
      out.write("            <label>Category:</label><input type=\"text\" id=\"editCategory\" name=\"update_category\"><br>\n");
      out.write("            <label>Manager SIN:</label><input type=\"text\" id=\"editManager\" name=\"update_manager\"><br>\n");
      out.write("            <input type=\"submit\" name=\"action\" value=\"Update\">\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");

    String action = request.getParameter("action");
    Connection db = null;
    PreparedStatement ps = null;

    try {
        if (action != null) {
            Class.forName("org.postgresql.Driver");
            db = DriverManager.getConnection("jdbc:postgresql://localhost:5432/e_hotel_system", "postgres", "password");

            if (action.equals("Insert")) {
                String sql = "INSERT INTO hotels (hotel_name, chain_name, hotel_address, stars, area, category, manager_sin) VALUES (?, ?, ?, ?::numeric, ?, ?, ?)";
                ps = db.prepareStatement(sql);
                ps.setString(1, request.getParameter("insert_name"));
                ps.setString(2, request.getParameter("insert_chain"));
                ps.setString(3, request.getParameter("insert_address"));
                ps.setString(4, request.getParameter("insert_stars"));
                ps.setString(5, request.getParameter("insert_area"));
                ps.setString(6, request.getParameter("insert_category"));
                ps.setString(7, request.getParameter("insert_manager"));
                ps.executeUpdate();
                out.println("<p style='color:green;'>Hotel inserted successfully.</p>");
            } else if (action.equals("Update")) {
                String sql = "UPDATE hotels SET hotel_name=?, chain_name=?, hotel_address=?, stars=?::numeric, area=?, category=?, manager_sin=? WHERE hotel_id=?::int";

                ps = db.prepareStatement(sql);
                ps.setString(1, request.getParameter("update_name"));
                ps.setString(2, request.getParameter("update_chain"));
                ps.setString(3, request.getParameter("update_address"));
                ps.setString(4, request.getParameter("update_stars"));
                ps.setString(5, request.getParameter("update_area"));
                ps.setString(6, request.getParameter("update_category"));
                ps.setString(7, request.getParameter("update_manager"));
                ps.setString(8, request.getParameter("update_id"));
                ps.executeUpdate();
                out.println("<p style='color:green;'>Hotel updated successfully.</p>");
            } else if (action.equals("Delete")) {
                String sql = "DELETE FROM hotels WHERE hotel_id=?::int";
                ps = db.prepareStatement(sql);
                ps.setString(1, request.getParameter("delete_id"));
                ps.executeUpdate();
                out.println("<p style='color:green;'>Hotel deleted successfully.</p>");
            }
        }
    } catch (Exception e) {
        out.println("<p style='color:red;'>Error: " + e.getMessage() + "</p>");
    } finally {
        if (ps != null) ps.close();
        if (db != null) db.close();
    }

      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
