/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-05-07 17:35:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class manageCustomers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Manage Customers</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; padding: 20px; background: #f9f9f9; }\n");
      out.write("        h2 { color: #333; }\n");
      out.write("        .nav { background: #eaf7ea; padding: 10px; margin-bottom: 20px; border-radius: 5px; }\n");
      out.write("        .nav a { margin-right: 15px; color: #4cae4c; font-weight: bold; text-decoration: none; }\n");
      out.write("        .card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 30px; }\n");
      out.write("        label { display: inline-block; width: 100px; margin-bottom: 10px; }\n");
      out.write("        input[type=\"text\"] { width: 250px; padding: 6px; border: 1px solid #ccc; border-radius: 4px; margin-bottom: 10px; }\n");
      out.write("        input[type=\"submit\"], button { background: #5cb85c; color: white; border: none; padding: 8px 12px; border-radius: 4px; cursor: pointer; }\n");
      out.write("        input[type=\"submit\"]:hover, button:hover { background: #4cae4c; }\n");
      out.write("        table { width: 100%; border-collapse: collapse; background: white; border-radius: 5px; overflow: hidden; }\n");
      out.write("        th, td { padding: 10px; border-bottom: 1px solid #ddd; text-align: left; }\n");
      out.write("        th { background-color: #f2f2f2; }\n");
      out.write("        tr:hover { background-color: #f1f1f1; }\n");
      out.write("        .modal { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); justify-content: center; align-items: center; }\n");
      out.write("        .modal-content { background: white; padding: 20px; border-radius: 5px; width: 400px; }\n");
      out.write("        .close { float: right; cursor: pointer; color: red; font-weight: bold; }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        function openEditModal(sin, email, fname, lname, address) {\n");
      out.write("            document.getElementById(\"editSin\").value = sin;\n");
      out.write("            document.getElementById(\"editEmail\").value = email;\n");
      out.write("            document.getElementById(\"editFname\").value = fname;\n");
      out.write("            document.getElementById(\"editLname\").value = lname;\n");
      out.write("            document.getElementById(\"editAddress\").value = address;\n");
      out.write("            document.getElementById(\"editModal\").style.display = \"flex\";\n");
      out.write("        }\n");
      out.write("        function closeModal() {\n");
      out.write("            document.getElementById(\"editModal\").style.display = \"none\";\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"nav\">\n");
      out.write("    <a href=\"index.jsp\">Main Page</a>\n");
      out.write("    <a href=\"manageCustomers.jsp\">Manage Customers</a>\n");
      out.write("    <a href=\"manageEmployees.jsp\">Manage Employees</a>\n");
      out.write("    <a href=\"manageHotels.jsp\">Manage Hotels</a>\n");
      out.write("    <a href=\"manageRooms.jsp\">Manage Rooms</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<h2>Manage Customers</h2>\n");
      out.write("\n");
      out.write("<!-- INSERT CUSTOMER -->\n");
      out.write("<div class=\"card\">\n");
      out.write("    <h3>Insert Customer</h3>\n");
      out.write("    <form method=\"post\">\n");
      out.write("        <label>SIN:</label><input type=\"text\" name=\"insert_sin\" required><br>\n");
      out.write("        <label>Email:</label><input type=\"text\" name=\"insert_email\" required><br>\n");
      out.write("        <label>First Name:</label><input type=\"text\" name=\"insert_fname\" required><br>\n");
      out.write("        <label>Last Name:</label><input type=\"text\" name=\"insert_lname\" required><br>\n");
      out.write("        <label>Address:</label><input type=\"text\" name=\"insert_address\" required><br>\n");
      out.write("        <input type=\"submit\" name=\"action\" value=\"Insert\">\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Display All Customers -->\n");
      out.write("<table>\n");
      out.write("    <tr>\n");
      out.write("        <th>SIN</th><th>Email</th><th>First Name</th><th>Last Name</th><th>Address</th><th>Actions</th>\n");
      out.write("    </tr>\n");
      out.write("    ");

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/e_hotel_system", "postgres", "password");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM customer");
            while (rs.next()) {
                String sin = rs.getString("sin");
                String email = rs.getString("email");
                String fname = rs.getString("firstname");
                String lname = rs.getString("lastname");
                String address = rs.getString("address");
    
      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td>");
      out.print( sin );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( email );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( fname );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( lname );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( address );
      out.write("</td>\n");
      out.write("        <td>\n");
      out.write("            <button onclick=\"openEditModal('");
      out.print( sin );
      out.write("', '");
      out.print( email );
      out.write("', '");
      out.print( fname );
      out.write("', '");
      out.print( lname );
      out.write("', '");
      out.print( address );
      out.write("')\">Edit</button>\n");
      out.write("            <form method=\"post\" style=\"display:inline;\">\n");
      out.write("                <input type=\"hidden\" name=\"delete_sin\" value=\"");
      out.print( sin );
      out.write("\"/>\n");
      out.write("                <input type=\"submit\" name=\"action\" value=\"Delete\" onclick=\"return confirm('Are you sure you want to delete this customer?');\"/>\n");
      out.write("            </form>\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("    ");

            }
        } catch (Exception e) {
            out.println("<tr><td colspan='6'>Error loading customers: " + e.getMessage() + "</td></tr>");
        } finally {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (conn != null) conn.close();
        }
    
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<!-- Edit Modal -->\n");
      out.write("<div id=\"editModal\" class=\"modal\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\n");
      out.write("        <h3>Edit Customer</h3>\n");
      out.write("        <form method=\"post\">\n");
      out.write("            <input type=\"hidden\" id=\"editSin\" name=\"update_sin\">\n");
      out.write("            <label>Email:</label>\n");
      out.write("            <input type=\"text\" id=\"editEmail\" name=\"update_email\">\n");
      out.write("            <label>First Name:</label>\n");
      out.write("            <input type=\"text\" id=\"editFname\" name=\"update_fname\">\n");
      out.write("            <label>Last Name:</label>\n");
      out.write("            <input type=\"text\" id=\"editLname\" name=\"update_lname\">\n");
      out.write("            <label>Address:</label>\n");
      out.write("            <input type=\"text\" id=\"editAddress\" name=\"update_address\">\n");
      out.write("            <input type=\"submit\" name=\"action\" value=\"Update\">\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");

    String action = request.getParameter("action");
    Connection db = null;
    PreparedStatement ps = null;

    try {
        if (action != null) {
            Class.forName("org.postgresql.Driver");
            db = DriverManager.getConnection("jdbc:postgresql://localhost:5432/e_hotel_system", "postgres", "password");

            if (action.equals("Insert")) {
                String sql = "INSERT INTO customer (sin, email, firstname, lastname, address) VALUES (?, ?, ?, ?, ?)";
                ps = db.prepareStatement(sql);
                ps.setString(1, request.getParameter("insert_sin"));
                ps.setString(2, request.getParameter("insert_email"));
                ps.setString(3, request.getParameter("insert_fname"));
                ps.setString(4, request.getParameter("insert_lname"));
                ps.setString(5, request.getParameter("insert_address"));
                ps.executeUpdate();
                out.println("<p style='color:green;'>Customer inserted successfully.</p>");
            }

            if (action.equals("Update")) {
                String sql = "UPDATE customer SET email=?, firstname=?, lastname=?, address=? WHERE sin=?";
                ps = db.prepareStatement(sql);
                ps.setString(1, request.getParameter("update_email"));
                ps.setString(2, request.getParameter("update_fname"));
                ps.setString(3, request.getParameter("update_lname"));
                ps.setString(4, request.getParameter("update_address"));
                ps.setString(5, request.getParameter("update_sin"));
                ps.executeUpdate();
                out.println("<p style='color:green;'>Customer updated successfully.</p>");
            }

            if (action.equals("Delete")) {
                String sql = "DELETE FROM customer WHERE sin=?";
                ps = db.prepareStatement(sql);
                ps.setString(1, request.getParameter("delete_sin"));
                ps.executeUpdate();
                out.println("<p style='color:green;'>Customer deleted successfully.</p>");
            }
        }
    } catch (Exception e) {
        out.println("<p style='color:red;'>Error: " + e.getMessage() + "</p>");
    } finally {
        if (ps != null) ps.close();
        if (db != null) db.close();
    }

      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
